# Project information
site_name: "DockSTARTer"
site_description: "DockSTARTer helps you get started with home server apps running in Docker."
site_author: "GhostWriters"
site_url: "https://dockstarter.com"

# Repository
repo_name: "GhostWriters/DockSTARTer"
repo_url: "https://github.com/GhostWriters/DockSTARTer"
edit_uri: "https://github.com/GhostWriters/DockSTARTer.com/edit/master/docs/"

# Copyright
copyright: "Copyright &copy; 2018 - 2019 GhostWriters"

# Configuration
theme:
  name: "material"
  language: "en"
  palette:
    primary: "blue grey"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: "img/icon.png"
  favicon: "img/favicon.ico"

# Navigation
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Basics:
      - Available Applications: basics/available-apps.md
      - How to Migrate to DS: basics/migration.md
      - Frequently Asked Questions: basics/faq.md
      - Port Conflicts: basics/port-conflicts.md
  - Advanced:
      - Advanced Usage: advanced/advanced-usage.md
      - Backups: advanced/backups.md
      - Macvlan Networking: advanced/macvlan.md
      - Overrides: advanced/overrides.md
      - Setting Up a Domain: advanced/domain-info.md
      - SMB Mounting: advanced/smb-mounting.md
      - Technical Info: advanced/technical-info.md
      - VPN Information: advanced/vpn-info.md
      - Uninstall: advanced/uninstall.md
  - App Specifics:
      - AirdcPP: apps/airdcpp.md
      - Airsonic: apps/airsonic.md
      - Bazarr: apps/bazarr.md
      - Beets: apps/beets.md
      - Bitwarden: apps/bitwarden.md
      - Booksonic: apps/booksonic.md
      - BookStack: apps/bookstack.md
      - CalibreWeb: apps/calibreweb.md
      - CloudCMD: apps/cloudcmd.md
      - CloudFlareDDNS: apps/cloudflareddns.md
      - CouchPotato: apps/couchpotato.md
      - Dasshio: apps/dasshio.md
      - DDClient: apps/ddclient.md
      - Deluge: apps/deluge.md
      - DelugeVPN: apps/delugevpn.md
      - DuckDNS: apps/duckdns.md
      - Duplicati: apps/duplicati.md
      - Emby: apps/emby.md
      - Filebot: apps/filebot.md
      - FreshRSS: apps/freshrss.md
      - Glances: apps/glances.md
      - Grafana: apps/grafana.md
      - Guacamole: apps/guacamole.md
      - h5ai: apps/h5ai.md
      - HandBrake: apps/handbrake.md
      - Headphones: apps/headphones.md
      - Heimdall: apps/heimdall.md
      - HomeAssistant: apps/homeassistant.md
      - HTPCManager: apps/htpcmanager.md
      - Hydra2: apps/hydra2.md
      - InfluxDB: apps/influxdb.md
      - Jackett: apps/jackett.md
      - Jellyfin: apps/jellyfin.md
      - LazyLibrarian: apps/lazylibrarian.md
      - LetsEncrypt: apps/letsencrypt.md
      - Lidarr: apps/lidarr.md
      - Logarr: apps/logarr.md
      - LogitechMediaServer: apps/logitechmediaserver.md
      - MakeMKV: apps/makemkv.md
      - MariaDB: apps/mariadb.md
      - McMyAdmin2: apps/mcmyadmin2.md
      - Medusa: apps/medusa.md
      - Monitorr: apps/monitorr.md
      - Muximux: apps/muximux.md
      - Mylar: apps/mylar.md
      - netdata: apps/netdata.md
      - Nextcloud: apps/nextcloud.md
      - NZBGet: apps/nzbget.md
      - NZBGetVPN: apps/nzbgetvpn.md
      - Ombi: apps/ombi.md
      - OpenVPNAS: apps/openvpnas.md
      - Organizr: apps/organizr.md
      - Ouroboros: apps/ouroboros.md
      - phpMyAdmin: apps/phpmyadmin.md
      - PiHole: apps/pihole.md
      - Plex: apps/plex.md
      - PlexRequests: apps/plexrequests.md
      - Portainer: apps/portainer.md
      - PortainerAgent: apps/portaineragent.md
      - pyLoad: apps/pyload.md
      - qBittorrent: apps/qbittorrent.md
      - qBittorrentVPN: apps/qbittorrentvpn.md
      - QuasselCore: apps/quasselcore.md
      - QuasselWeb: apps/quasselweb.md
      - Radarr: apps/radarr.md
      - ResilioSync: apps/resiliosync.md
      - rTorrentVPN: apps/rtorrentvpn.md
      - ruTorrent: apps/rutorrent.md
      - SABnzbd: apps/sabnzbd.md
      - SABnzbdVPN: apps/sabnzbdvpn.md
      - Samba: apps/samba.md
      - SickChill: apps/sickchill.md
      - SiCKRAGE: apps/sickrage.md
      - SmokePing: apps/smokeping.md
      - Sonarr: apps/sonarr.md
      - Syncthing: apps/syncthing.md
      - Tautulli: apps/tautulli.md
      - Telegraf: apps/telegraf.md
      - TheLounge: apps/thelounge.md
      - Transmission: apps/transmission.md
      - TransmissionVPN: apps/transmissionvpn.md
      - TTRSS: apps/ttrss.md
      - Tvheadend: apps/tvheadend.md
      - Ubooquity: apps/ubooquity.md
      - Unifi: apps/unifi.md
      - UnifiController: apps/unificontroller.md
      - Varken: apps/varken.md
      - vsftpd: apps/vsftpd.md
      - Watchtower: apps/watchtower.md
      - ZNC: apps/znc.md
